# gdu
# Autogenerated from man page /usr/share/man/man1/gdu.1.gz
complete -c gdu -s h -l help
complete -c gdu -s i -l ignore-dirs -d 'paths to ignore (separated by comma)'
complete -c gdu -s I -l ignore-dirs-pattern -d 'ignore (separated by comma)'
complete -c gdu -s X -l ignore-from -d 'ignore from file'
complete -c gdu -s l -l log-file
complete -c gdu -s m -l max-cores
complete -c gdu -s c -l no-color
complete -c gdu -s x -l no-cross -d boundaries
complete -c gdu -s H -l no-hidden -d '(beginning with dot)'
complete -c gdu -s L -l follow-symlinks -d 'files, i. e'
complete -c gdu -s n -l non-interactive -d 'interactive mode'
complete -c gdu -s p -l no-progress -d 'non-interactive mode'
complete -c gdu -s u -l no-unicode -d '(for size bar)'
complete -c gdu -s s -l summarize -d 'non-interactive mode'
complete -c gdu -s d -l show-disks
complete -c gdu -s a -l show-apparent-size
complete -c gdu -s C -l show-item-count -d 'in directory'
complete -c gdu -s M -l show-mtime -d 'in directory'
complete -c gdu -l si -d 'instead of binary prefixes (KiB, MiB, GiB)'
complete -c gdu -l no-prefix -d 'prefixes (SI or binary) in non-interactive mode'
complete -c gdu -l no-mouse
complete -c gdu -l no-delete
complete -c gdu -s f -l input-file -d 'If the file is [dq]-[dq], read from standard input'
complete -c gdu -s o -l output-file -d 'If the file is [dq]-[dq], write to standard output'
complete -c gdu -l config-file
complete -c gdu -l write-config -d '(default is $HOME/. gdu. yaml)'
complete -c gdu -s g -l const-gc -d 'collection during analysis with constant level set by GOGC'
complete -c gdu -l enable-profiling -d 'and provide it on http://localhost:6060/debug/pprof/'
complete -c gdu -l use-storage -d 'analysis data (experimental)'
complete -c gdu -s r -l read-from-storage -d 'from persistent key-value storage'
complete -c gdu -s v -l version -d 'FILE FLAGS Files and directories may be prefixed by a one-character flag with…'

