# ani-cli
# Autogenerated from man page /usr/share/man/man1/ani-cli.1.gz
complete -c ani-cli -s e -l episode -s r -l range -d 'Specify the episode numbers to watch'
complete -c ani-cli -s c -l continue -d 'Continue watching anime from history'
complete -c ani-cli -s d -l download -d 'Download episode'
complete -c ani-cli -s D -l delete -d 'Delete history'
complete -c ani-cli -s S -l select-nth -d 'Selects nth entry'
complete -c ani-cli -s h -l help -d 'Show summary of options'
complete -c ani-cli -s q -l quality -d 'Set the video quality.  Default quality is best'
complete -c ani-cli -s s -l syncplay -d 'Watch anime together with friends, using Syncplay (works with mpv only)'
complete -c ani-cli -s U -l update -d 'Fetch update from github'
complete -c ani-cli -s v -l vlc -d 'Use VLC as the media player'
complete -c ani-cli -s N -l non-interactive -d 'Disable the interactive menu'
complete -c ani-cli -l dub -d 'Play the dubbed version'
complete -c ani-cli -l rofi -d 'Use rofi instead of fzf for the interactive menu'
complete -c ani-cli -l skip -d 'Use ani-skip to skip the intro of the episode (mpv only)'
complete -c ani-cli -l no-detach -d 'Don\'t detach the player (useful for in-terminal playback, mpv only)'
complete -c ani-cli -l skip-title -d 'Specify the title to use for ani-skip'

