# cbonsai
# Autogenerated from man page /usr/share/man/man1/cbonsai.1.gz
complete -c cbonsai -s t -l time -d 'in live mode, wait TIME secs between steps of growth (must be larger than 0) …'
complete -c cbonsai -s i -l infinite -d 'infinite mode: keep growing trees'
complete -c cbonsai -s w -l wait -d 'in infinite mode, wait TIME between each tree generation [default: 4. 00]'
complete -c cbonsai -s S -l screensaver -d 'screensaver mode; equivalent to -liWC and quit on any keypress'
complete -c cbonsai -s m -l message -d 'attach message next to the tree'
complete -c cbonsai -s b -l base -d 'ascii-art plant base to use, 0 is none'
complete -c cbonsai -s c -l leaf -d 'list of comma-delimited strings randomly chosen for leaves'
complete -c cbonsai -s M -l multiplier -d 'branch multiplier; higher -> more branching (0-20) [default: 5]'
complete -c cbonsai -s L -l life -d 'life; higher -> more growth (0-200) [default: 32]'
complete -c cbonsai -s p -l print -d 'print tree to terminal when finished'
complete -c cbonsai -s s -l seed -d 'seed random number generator'
complete -c cbonsai -s W -l save -d 'save progress to file [default: ~/. cache/cbonsai]'
complete -c cbonsai -s C -l load -d 'load progress from file [default: ~/. cache/cbonsai]'
complete -c cbonsai -s v -l verbose -d 'increase output verbosity'
complete -c cbonsai -s h -l help -d 'show help'

